{% set version = "1.3-16" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dismo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dismo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dismo/dismo_{{ version }}.tar.gz
  sha256: e79623a75514a54a6f4328a7939e1828c6fcd7d13d87e82ec030362af4632053

build:
  number: 1
  # Skip win due to r-terra not being available: https://github.com/conda-forge/r-terra-feedstock/issues/61
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-raster >=3.5_21
    - r-sp >=1.4_5
    - r-terra >=1.5_34
  run:
    - r-base
    - r-rcpp
    - r-raster >=3.5_21
    - r-sp >=1.4_5
    - r-terra >=1.5_34

test:
  commands:
    - $R -e "library('dismo')"           # [not win]
    - "\"%R%\" -e \"library('dismo')\""  # [win]

about:
  home: http://rspatial.org/sdm/
  license: GPL-3.0-or-later
  summary: Functions for species distribution modeling, that is, predicting entire geographic distributions form occurrences at a number of sites and the environment at these sites.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsoranzo
