{% set version = '1.1-4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dismo
  version: {{ version|replace("-", "_") }}

source:
  fn: dismo_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/dismo_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/dismo/dismo_{{ version }}.tar.gz
  sha256: f2110f716cd9e4cca5fd2b22130c6954658aaf61361d2fe688ba22bbfdfa97c8

build:
  merge_build_host: True  # [win]
  number: 1004
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-raster >=2.5_2
    - r-sp >=1.2_0

  run:
    - r-base
    - r-raster >=2.5_2
    - r-sp >=1.2_0

test:
  commands:
    - $R -e "library('dismo')"  # [not win]
    - "\"%R%\" -e \"library('dismo')\""  # [win]

about:
  home: http://rspatial.org/sdm/
  license: GPL (>= 3)
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
  summary: Functions for species distribution modeling, that is, predicting entire geographic
    distributions form occurrences at a number of sites and the environment at these
    sites.

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsoranzo
