{% set version = "1.3-8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dismo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dismo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dismo/dismo_{{ version }}.tar.gz
  sha256: 66e360f5a5a9f23697a7dd51ba7490d9bb465856692934ae1b20d1b41d99bc9d

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-raster >=3.5_21
    - r-sp >=1.4_5
    - r-terra >=1.5_34
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-raster >=3.5_21
    - r-sp >=1.4_5
    - r-terra >=1.5_34

test:
  commands:
    - $R -e "library('dismo')"           # [not win]
    - "\"%R%\" -e \"library('dismo')\""  # [win]

about:
  home: http://rspatial.org/sdm/
  license: GPL-3.0-or-later
  summary: Functions for species distribution modeling, that is, predicting entire geographic distributions form occurrences at a number of sites and the environment at these sites.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsoranzo
