appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LvbxgBra8uLE7+gXbKaTRSnzMJxW77tJERlgSt1pViUUj5kMFMcVzQ8fBwKF6SwaPNK/FYsVg3b6qb77k/DL3w5yIo+xGIEemRA5OwG70pJpdwFCVDqdp8STF/TV4XMu9LXTfLmzFdO5wwUM/Ng82NMIPeTDlTC2P2ACqfsyPTu2cox7DsQ8vt+QdQv59w6chd9ojX+Nd86VroFkfHqLbdhsjhWbSNbDw1ZvPpeTUvUUMflKS1leO+PBYhQJQgOCV4RyOy6t22+hKbLMuxdfaWXUJ4yi0jxIC42eKs4A4cRDIPI79Orduvrs/VdSQ4ZkOU2pvFldUaYSOavurwBD8j7IQWUpn99Lf+W4wAempaCD4jPWXtXjR/vJcm+C7su6ar0jO4i4qHNOkC5vXUfztZqG0HdmQO7CYbrPeXlLekdPgIA4cpg2cQmFeEa6p4b6IteHmO5eYlplWdWZHiklleelWcoWs/zBhxoFFzcvv1qSvikjSGFsZTle4ucYmHwFwYQVfJmq+H2MQ9O3OSgFYC6uY39euTEn+Nc59SW1q9ekeINv1CYkbELjAMOkQ1ePcgn8OLEjcX4mrP+XQi+xo3V3NI/hVPZVRWxGcU51JSErbm+uZPLJ3MraKOytOGuLKZThSWkapQqQnrFKQEijTrxCv6fDbyYK7sLz38aTZ8E=}
