travis:
  secure:
    BINSTAR_TOKEN: J3WNyxM2NKR+T37bixg2gLmqbSO2sVK06eCfoHJ0VBxyHEriapIOjupGJZHTdFADnvV5O6ns//ZspEu796xBjJrpZzbg4aL1V8QM2jPOObosPcWcqAh7zweo2EqxzE62jgX6v0UQKcveUphBPCdK+/2RiCAh3pnaQ3lUi+MQUNjWh3vaMBy6WAlNqbOBbzUztyR8HxIfqoUEDtBr2pI/w/TJN4OX2ZitsyTaJw1B54Fs2dB6j7kd2MDaCAEFIa8m3+ZSh/rtCEIc1PZWqU7tsZj2z/3kKKzOUIkONVbH8el+ZCqzeXBm7U+wgyPDGz77I3pkjN5KvAVgtLVpu012/Z1MVcQ7uK9LPE4z1FnCVlOvu6xrxgIZntiGxt5QhN4ujOOoz12wklJLn/2IESHom+74ApPV2oH23fPfD5O2c9eEuZGxqbRQB1PrIjhnb20sBdERZp/9473D5psyFLBSvhXgwFb00CBtxrm2sOBpcj3yifbgNmEJMPwMd08yeZn9t1Kb4qjB25VOnKZJ/Qfrce1Su5ewSbFKdS/qEulnbY19bJt09YVgG/jjf84lBAswaQ36f9OtlUZISWThtbjbnu1AZ0YKAqeyqLTRvR8cOfsS2zSPwgU7JQZclVmAGFvUrkvw34qCgqpdBioKxdfyDGMQoXRuBDnVUsLD9Y893/U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
