travis:
  secure:
    BINSTAR_TOKEN: Aimv3vlpGZqncZcOzZbbC42ImnAntG/Sl9hzvSqmiGZhe8QdWqkouZ+z5aVSdho+rY3tZHWMoxWTCIu4WjxQKqUSoQw/pF8p6xyisQGljqIEtko3x8XEQqAAeCqsvZ2EWFU/UTJMUMESOz0itUQYYnJHCUH4ZY2HnP199YbLQSMLL8/NjwC45POPBc0UvDk1Om1MIf/7f1NgHBsdOvQ4eCa/nUDo8JQjbYkmgAd+UKDXHusIDfo/8sjmJrnRsybxcBIzcqQccuq6Hacju9QLC+FiCn35kq7uN6yDKkoqhK+l3MbRFLFgrObZKr2HWyrPFxYm2CALX4X/PVj3E7eyFsYTLEcTQGsPHAl9JVbzHYrFaaLA+6GeuO0yxUy0M2fin57aMmYlxNspOOtondMUniQSxdrwigprVdjbF1x8FGGScdX2Gc1XQbbnaxjsiTCQ0YQTHj1DH/SSPX3rG0MbjeWWQF/D4zERQ1djxtcbdlHdUzYKz7Pbj4iGDgovfX/CTKZzdzHhjuqYvtjVp54hs2i8lfVmGMjPX5SjlsWwqVM45ZgDwP3VFYf1GOGD6sUk6vhOR+iowZ/TLMPbg+PmIS5OT1rShZCHJGc2evD89fRbtynqJXTfe9io+TQf2Zwd0dgb16IdLADz2xcFyOY2wpQOnvHjNu5T1usqI4vQviQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
