travis:
  secure:
    BINSTAR_TOKEN: Fnr0zmMobPH+kygjlJ4PJSYF4VNCEdKCZVmBwgtjS2C9+oJfkMsVMaGtax2C2lpGfwuqVffthRBqXrkaXgcsbetFTHwEpHmSbylTzyNIQ/qYXNU8ncLP7Ut8eAUU2DjdopSQY/Ht0mZ2qy9rYD9cyLiVHybCkBrEPSI76EfKmcH9xZ62hcjiAIOmo+KkGNjrIy5HUJxsu+U61CltQk8v3W94d0N4kFkbnpEQizrsn+vPT8fRQn1l2MUrMrc5ZGM9jFn3vETDgkiwnGyZ2FPAQmX8qmRXHMdWTnTZO+IpEbmLUdOXnbJop+A80TVGBY9GRhQ+vY4Ur6l3wDGaJoRVIUGtmh7q4hqqF4080t/YDMMaTGLuse8s2R7psy5ygsRvWJpH68rrqOU2dUfEk2HRThypHryp7CHKZnD55bfXbYEtK1DI9sH4yB0zgfg3hmyrkKMbcbersPAeEKu2yjeIhu+6lbyEq2kUjXrjMpAS6oATrOTl5+M/RdxRHsBYjLljiadKS0L4f2I1I3cqsyuLiWt/DrowBNIov8Wsbf63/AgFBI4yn6OQ6S6Vu/iMv3AruwxKRh/+/sHxqVvAZx3aOvfEUbvHiyzkxeEU5D3ZYhxeX2EiKCr01S+32zQXa00zeBF/QgucFHrWs28RtvzcYTDpNm69YIxH4wurtA9tOiQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
